// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsLfkKwwiFU8MHOdowcDindtrjHH-bSI',
    appId: '1:229376288542:web:147d9df33be3a92446cb0f',
    messagingSenderId: '229376288542',
    projectId: 'my-test-app-flavors-stage',
    authDomain: 'my-test-app-flavors-stage.firebaseapp.com',
    storageBucket: 'my-test-app-flavors-stage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65qDw07skZbZ3m3nD99uWWiUkLpt6v9U',
    appId: '1:229376288542:android:e8bc239e22992f2f46cb0f',
    messagingSenderId: '229376288542',
    projectId: 'my-test-app-flavors-stage',
    storageBucket: 'my-test-app-flavors-stage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj49lJDvBRMT1kipQySYNuqInniupFWOA',
    appId: '1:229376288542:ios:0ee74ef9d943646a46cb0f',
    messagingSenderId: '229376288542',
    projectId: 'my-test-app-flavors-stage',
    storageBucket: 'my-test-app-flavors-stage.appspot.com',
    iosClientId: '229376288542-rcbpu7rd7tvkf6jpohik64njm4qjnpmn.apps.googleusercontent.com',
    iosBundleId: 'com.codewithandrea.my-test-app-flavors.stg',
  );
}
