// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5q6FCOoqvkFHIbenddg7FyN4JWYQIK8',
    appId: '1:245775840332:web:515806a790058f67def0e9',
    messagingSenderId: '245775840332',
    projectId: 'my-test-app-flavors-devel',
    authDomain: 'my-test-app-flavors-devel.firebaseapp.com',
    storageBucket: 'my-test-app-flavors-devel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFsEO2c17yKKZcrVBHGF-Fq3OJ_6g5Eh8',
    appId: '1:245775840332:android:f3ae64e4721c3b6ddef0e9',
    messagingSenderId: '245775840332',
    projectId: 'my-test-app-flavors-devel',
    storageBucket: 'my-test-app-flavors-devel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIBcH-2wGeWXK9tdgsBejk4AyCUwoXo7M',
    appId: '1:245775840332:ios:c3a1b0c0af6fed4bdef0e9',
    messagingSenderId: '245775840332',
    projectId: 'my-test-app-flavors-devel',
    storageBucket: 'my-test-app-flavors-devel.appspot.com',
    iosClientId: '245775840332-g8dps4u7uvcvtpn4pb51fap2uivsnih1.apps.googleusercontent.com',
    iosBundleId: 'com.codewithandrea.my-test-app-flavors.dev',
  );
}
